# Generated by Django 4.2.6 on 2023-11-08 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=32)),
                ('activity_desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=32, unique=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(max_length=16)),
                ('limit', models.BooleanField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=32, unique=True)),
                ('group_desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=10)),
                ('user_age', models.IntegerField()),
                ('user_gender', models.SmallIntegerField(choices=[(1, '男'), (0, '女')])),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('user_signature', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_flag', models.BooleanField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('uid', 'gid')},
            },
        ),
        migrations.CreateModel(
            name='UserInActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('uid', 'aid')},
            },
        ),
        migrations.CreateModel(
            name='UserEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_time', models.DateTimeField()),
                ('lend_amount', models.IntegerField()),
                ('is_return', models.BooleanField(default=False)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipment')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('eid', 'uid', 'lend_time')},
            },
        ),
        migrations.CreateModel(
            name='UserCreateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('aid',)},
            },
        ),
        migrations.CreateModel(
            name='UserApplyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(1, '已接受'), (2, '已拒绝'), (0, '申请中')])),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('uid', 'gid', 'apply_time')},
            },
        ),
        migrations.CreateModel(
            name='GroupEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_time', models.DateTimeField()),
                ('lend_amount', models.IntegerField()),
                ('is_return', models.BooleanField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipment')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
            options={
                'unique_together': {('eid', 'gid', 'lend_time')},
            },
        ),
        migrations.CreateModel(
            name='GroupCreateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
            options={
                'unique_together': {('aid',)},
            },
        ),
        migrations.CreateModel(
            name='ActivityUseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field')),
            ],
            options={
                'unique_together': {('fid', 'start_time'), ('fid', 'end_time'), ('aid',)},
            },
        ),
    ]
