# Generated by Django 4.2.6 on 2023-11-18 17:06

import api.system.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=128)),
                ('maximum', models.IntegerField()),
                ('picture', models.ImageField(null=True, storage=api.system.storage.ImageStorage(), upload_to='images/activity/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=32, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('picture', models.ImageField(null=True, storage=api.system.storage.ImageStorage(), upload_to='images/equipment/')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(max_length=16)),
                ('limit', models.BooleanField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=32, unique=True)),
                ('group_desc', models.CharField(max_length=128)),
                ('maximum', models.IntegerField()),
                ('picture', models.ImageField(null=True, storage=api.system.storage.ImageStorage(), upload_to='images/group/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=10)),
                ('user_age', models.IntegerField()),
                ('user_gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')])),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('user_signature', models.CharField(blank=True, default='', max_length=128)),
                ('picture', models.ImageField(null=True, storage=api.system.storage.ImageStorage(), upload_to='images/user/')),
            ],
        ),
        migrations.CreateModel(
            name='UserInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(2, '成员'), (0, '创建人'), (1, '管理员')])),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserInActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lend_amount', models.IntegerField()),
                ('is_return', models.SmallIntegerField(choices=[(0, '未归还'), (2, '已归还')])),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipment')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCreateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserApplyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, '申请中'), (1, '已接受'), (2, '已拒绝')])),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lend_amount', models.IntegerField()),
                ('is_return', models.SmallIntegerField(choices=[(0, '未归还'), (2, '已归还')])),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipment')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCreateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends1', to='api.user')),
                ('uid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityUseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field')),
            ],
        ),
        migrations.AddConstraint(
            model_name='useringroup',
            constraint=models.UniqueConstraint(fields=('uid', 'gid'), name='unique_user_in_group'),
        ),
        migrations.AddConstraint(
            model_name='userinactivity',
            constraint=models.UniqueConstraint(fields=('uid', 'aid'), name='unique_user_in_activity'),
        ),
        migrations.AddConstraint(
            model_name='userequipment',
            constraint=models.UniqueConstraint(fields=('eid', 'uid', 'start_time', 'end_time'), name='unique_user_equipment'),
        ),
        migrations.AddConstraint(
            model_name='usercreateactivity',
            constraint=models.UniqueConstraint(fields=('aid',), name='unique_user_create_activity'),
        ),
        migrations.AddConstraint(
            model_name='userapplygroup',
            constraint=models.UniqueConstraint(fields=('uid', 'gid', 'apply_time'), name='unique_user_apply_group'),
        ),
        migrations.AddConstraint(
            model_name='groupequipment',
            constraint=models.UniqueConstraint(fields=('eid', 'gid', 'start_time', 'end_time'), name='unique_group_equipment'),
        ),
        migrations.AddConstraint(
            model_name='groupcreateactivity',
            constraint=models.UniqueConstraint(fields=('aid',), name='unique_group_create_activity'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('uid1', 'uid2'), name='unique_friend'),
        ),
        migrations.AddConstraint(
            model_name='activityusefield',
            constraint=models.UniqueConstraint(fields=('aid',), name='unique_activity_user_field1'),
        ),
        migrations.AddConstraint(
            model_name='activityusefield',
            constraint=models.UniqueConstraint(fields=('fid', 'start_time'), name='unique_activity_user_field2'),
        ),
        migrations.AddConstraint(
            model_name='activityusefield',
            constraint=models.UniqueConstraint(fields=('fid', 'end_time'), name='unique_activity_user_field3'),
        ),
    ]
