# Generated by Django 4.2.6 on 2023-10-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=32, unique=True)),
                ('group_desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=10)),
                ('user_age', models.IntegerField()),
                ('user_gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')])),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('user_signature', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_flag', models.SmallIntegerField(choices=[(1, True), (0, False)])),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('uid', 'gid')},
            },
        ),
    ]
