# Generated by Django 4.2.6 on 2023-11-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupequipment',
            name='is_return',
            field=models.SmallIntegerField(choices=[(0, '未归还'), (2, '已归还')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (0, '女')]),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '申请中'), (2, '已拒绝'), (1, '已接受')]),
        ),
        migrations.AlterField(
            model_name='userequipment',
            name='is_return',
            field=models.SmallIntegerField(choices=[(0, '未归还'), (2, '已归还')], default=0),
        ),
        migrations.AlterField(
            model_name='useringroup',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '管理员'), (2, '成员'), (0, '创建人')]),
        ),
    ]
