# Generated by Django 4.2.6 on 2023-10-29 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringroup',
            name='manager_flag',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='UserApplyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
