# Generated by Django 4.2.6 on 2023-11-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_gender_alter_userapplygroup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupequipment',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupequipment',
            name='lend_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (0, '女')]),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '申请中'), (2, '已拒绝'), (1, '已接受')]),
        ),
        migrations.AlterField(
            model_name='userequipment',
            name='lend_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
