# Generated by Django 4.2.6 on 2023-10-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_pwd_user_password_alter_user_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (0, '女')]),
        ),
    ]
