# Generated by Django 4.2.6 on 2023-11-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_groupequipment_is_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(default=2135220, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='tag',
            field=models.CharField(default=123, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=2135220, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='tag',
            field=models.CharField(default=123, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupequipment',
            name='is_return',
            field=models.SmallIntegerField(choices=[(2, '已归还'), (0, '未归还')], default=0),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '申请中'), (1, '已接受'), (2, '已拒绝')]),
        ),
        migrations.AlterField(
            model_name='userequipment',
            name='is_return',
            field=models.SmallIntegerField(choices=[(2, '已归还'), (0, '未归还')], default=0),
        ),
        migrations.AlterField(
            model_name='useringroup',
            name='type',
            field=models.SmallIntegerField(choices=[(2, '成员'), (0, '创建人'), (1, '管理员')]),
        ),
    ]
