# Generated by Django 4.2.6 on 2023-10-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userapplygroup_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (0, '女')]),
        ),
    ]
