# Generated by Django 4.2.6 on 2023-10-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男')]),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.CharField(choices=[(0, '申请中'), (1, '已接受'), (2, '已拒绝')], max_length=8),
        ),
    ]
