# Generated by Django 4.2.6 on 2023-11-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_user_gender_alter_userapplygroup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已接受'), (2, '已拒绝'), (0, '申请中')]),
        ),
    ]
