# Generated by Django 4.2.6 on 2023-11-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_activity_creator_remove_activity_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '个人'), (1, '团体')]),
        ),
        migrations.AlterField(
            model_name='friendapply',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '申请中'), (1, '已接受'), (2, '已拒绝')]),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '申请中'), (1, '已接受'), (2, '已拒绝')]),
        ),
    ]
