# Generated by Django 4.2.6 on 2023-10-29 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_user_gender_alter_userapplygroup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (0, '女')]),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='apply_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.CharField(choices=[(2, '已拒绝'), (0, '申请中'), (1, '已接受')], max_length=8),
        ),
    ]
