# Generated by Django 4.2.6 on 2023-10-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男')]),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.CharField(choices=[(0, '申请中'), (2, '已拒绝'), (1, '已接受')], max_length=8),
        ),
    ]
