# Generated by Django 4.2.6 on 2023-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_user_gender_alter_userapplygroup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男')]),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.CharField(choices=[(2, '已拒绝'), (1, '已接受'), (0, '申请中')], max_length=8),
        ),
    ]
