# Generated by Django 4.2.6 on 2023-11-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.CharField(choices=[('1', '已接受'), ('2', '已拒绝'), ('0', '申请中')], max_length=8),
        ),
    ]
