# Generated by Django 4.2.6 on 2023-11-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_user_gender_alter_userapplygroup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已接受'), (0, '申请中'), (1, '已拒绝')], max_length=8),
        ),
    ]
