# Generated by Django 4.2.6 on 2023-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userapplygroup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(max_length=16)),
                ('limit', models.BooleanField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男')]),
        ),
        migrations.AlterField(
            model_name='userapplygroup',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已接受'), (0, '申请中'), (2, '已拒绝')], max_length=8),
        ),
    ]
